### ISSUE TITLE
Nowhere does it say what to do if you get an error running Update-AdfsCertificate -CertificateType: Token-Signing

### ISSUE THREAD

**Issue by cypherstream** [MicrosoftDocs/windowsserverdocs#3761]
Not a single article, blog or internet search explains what to do if the "auto" certificate did not automatically renew like the property states it should, and then a manual run of this PS command as admin when authenticated throws an error:

 Update-AdfsCertificate -CertificateType: Token-Signing
Update-AdfsCertificate : The server was unable to process the request due to an internal error.  For more information
about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the
&lt;serviceDebug&gt; configuration behavior) on the server in order to send the exception information back to the client, or
turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.
At line:1 char:1
+ Update-AdfsCertificate -CertificateType: Token-Signing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-AdfsCertificate], FaultException
    + FullyQualifiedErrorId : The server was unable to process the request due to an internal error.  For more informa
   tion about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from
  the &lt;serviceDebug&gt; configuration behavior) on the server in order to send the exception information back to the cl
 ient, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.,
Microsoft.IdentityServer.Management.Commands.UpdateCertificateCommand

Same error for token-decrypting cert update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993d83d2-922d-0b5d-42e4-ed86117dc3db
* Version Independent ID: dccf4daf-47bc-696e-672e-92d1a826346c
* Content: [Obtain and Configure Token Signing and Token Decryption Certificates for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ts-td-certs-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-TS-TD-certs-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-TS-TD-certs-ad-fs.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by th0u** [comment]
Had the same issue. Was related to "Certificate Authentication" ticked on in Authentication Methods on ADFS Server. After unticking, "Update-AdfsCertificate -CertificateType: Token-Signing" created the certificate w/o error.

**Comment by Weirdphish** [comment]
Also having the same issue. Were you able to resolve if so how? Had a look at th0u's suggestion but this was already unticked. Have ticket open with MS but nothing much from them so far. Any help appreciated.

**Comment by pvenkitaraman** [comment]
Also having the same issue, Ticket open with MS but nothing much. Any help is appreciated

**Comment by MichaelHall001** [comment]
I work at Microsoft.  I fixed this for a customer today. 

Rename it old and then lets make a new one.  You can use this PowerShell below. When you run the set command you should have it be domain\ADFS service account name.  It should make a new identical one with all the correct permissions.  

PS C:\Windows\system32> (Get-AdfsProperties).certificatesharingcontainer
CN=a45403ae-89a1-4314-892a-94a1fa86a689,CN=ADFS,CN=Microsoft,CN=Program Data,DC=mikehall,DC=xyz
PS C:\Windows\system32> Set-AdfsCertSharingContainer -ServiceAccount mikehall\serviceaccount01$
PS C:\Windows\system32>

 

![1](https://user-images.githubusercontent.com/90070115/132068138-670764b0-f015-4d99-acdf-00ca17bf9379.png)

**Comment by cypherstream** [comment]
Did that and it worked, recreated the container in adsi edit, but the token-signing and token-decrypting cert are still expired since 2020.  I try to run Update-ADFSCertificate -CertificateType token-signing and still get the same error.  Not sure if I just need to wait some time, reboot or restart any services, etc...  

Anyway its been like this for a long time and nothing is broken.  We can still sign into various apps against Azure AD and Azure AD Connect still syncs up on-prem to 365 without any issue.  We use a few SSO things against portal.azure.com as well as register Office via portal.office.com and theres no issues.  So maybe this is a moot point or not needed in our org.

**Comment by dknappettmsft** [comment]
Hi, thanks for the feedback.  The as others have done in this thread, if the output generates an error, it's best to contact Microsoft Support.  In this instance I notice you're adding a colon after the -CertificateType parameter, which is what the error you gave is saying: "InvalidData: (:)". In this instance I will close this issue.

#please-close

**Comment by ZeBix78** [comment]
> I work at Microsoft boii. I fixed this for a customer today.
> 
> My customer's token signing cert was about to expire. He wanted to run Update-AdfsCertificate.
> 
> This is how we fixed it. It has to do with the AdfsCertSharingContainer.
> 
> Rename it old and then make a new one. You can use this PowerShell below. When you run the set command you should have it be domain\ADFS service account name. It should make a new identical one with all the correct permissions.
> 
> PS C:\Windows\system32> (Get-AdfsProperties).certificatesharingcontainer CN=a45403ae-89a1-4314-892a-94a1fa86a689,CN=ADFS,CN=Microsoft,CN=Program Data,DC=mikehall,DC=xyz PS C:\Windows\system32> Set-AdfsCertSharingContainer -ServiceAccount mikehall\serviceaccount01$ PS C:\Windows\system32>
> 
> ![1](https://user-images.githubusercontent.com/90070115/132068138-670764b0-f015-4d99-acdf-00ca17bf9379.png)

THANK YOU.   

Found a lot of fantasist solutions for this issue, none of them worked.
This fixed the problem for us, many thanks.

**Comment by MichaelHall001** [comment]
Just run this part  (Get-AdfsProperties).certificatesharingcontainer

**Comment by hrometsch** [comment]
had the same issue and this great article saved my life

**Comment by th0u** [comment]
Hi,
my workaround (see above) did not work this time but the solution renaming the Container worked.

first I identified the guid
`(Get-AdfsProperties).certificatesharingcontainer`
then I renamed the Container using ADSI Edit. As we run multiple DCs across locations, I double checked that the rename was replicated before going ahead.

second, I ran
`Set-AdfsCertSharingContainer`
and typed in the account manually: domain\SRV-USER
Also I took in account that DC replication may take some time

third, after the container was visible again in ADSI Edit it ran
```
Update-AdfsCertificate -CertificateType: Token-Decrypting
Update-AdfsCertificate -CertificateType: Token-Signing

```
this time without error.

**Comment by MFenton1204** [comment]
Hey th0u, how did you identify/ verify the service account?
My ADFS was created before me so not sure what the service account was used to create it and I want to make sure when re- creating the container all is the same.

**Comment by th0u** [comment]
Use the service manager and search for service "Active Directory Federation Services" and identify user in Column "Log on As".
<img width="921" alt="image" src="https://user-images.githubusercontent.com/19540174/227733742-04241500-0b1f-4775-8a9a-89c76a3cf0d3.png">

**Comment by MFenton1204** [comment]
Th0u, thanks that worked great certs have been recreated and no issues, does ADFS automatically promote the new secondary to primary or do you need to run a PowerShell command?

**Comment by MFenton1204** [comment]
One more question, what if you use the wrong service account?

**Comment by MFenton1204** [comment]
Hey Zebix78, what if I used the wrong service account to create the certificate share container?? I need answer asap please.

**Comment by MFenton1204** [comment]
I ran the set-adfscertsharingcontainer -serviceaccount domain\correctedserviceaccount. But do I need to resend metadata to our relay companies? Seems to have broken my service account certificate for the external sites now showing “not secure” in web browser and getting HTTP404 error…need help ASAP!!!

**Comment by MFenton1204** [comment]
Hi, after I was able to do all of the steps above, I just again looked in the Certificate Sharing container and it appears to NOW contain different folders than when created, can anyone tell me why this is happening? we are also getting an  error when our users try to login to the sites (See attached photo....)
![CloudError](https://user-images.githubusercontent.com/128873804/229161937-4b4c4929-e406-46c8-946e-3af5ff654660.PNG)

Any help is really appreciate, I tried to call MS Suppport but they never answer seems they think they are to good to support users!!!!!

**Comment by mamehl** [comment]
> Hi, after I was able to do all of the steps above, I just again looked in the Certificate Sharing container and it appears to NOW contain different folders than when created, can anyone tell me why this is happening? we are also getting an error when our users try to login to the sites (See attached photo....) ![CloudError](https://user-images.githubusercontent.com/128873804/229161937-4b4c4929-e406-46c8-946e-3af5ff654660.PNG)
> 
> Any help is really appreciate, I tried to call MS Suppport but they never answer seems they think they are to good to support users!!!!!

Did you end up fixing this? I'm running into the same issues.

**Comment by mamehl** [comment]
> > Hi, after I was able to do all of the steps above, I just again looked in the Certificate Sharing container and it appears to NOW contain different folders than when created, can anyone tell me why this is happening? we are also getting an error when our users try to login to the sites (See attached photo....) ![CloudError](https://user-images.githubusercontent.com/128873804/229161937-4b4c4929-e406-46c8-946e-3af5ff654660.PNG)
> > Any help is really appreciate, I tried to call MS Suppport but they never answer seems they think they are to good to support users!!!!!
> 
> Did you end up fixing this? I'm running into the same issues.

Never mind. I was able to resolve it. You're required to rerun the proxy config wizard to complete the process, which hasn't been outlined in the above.

**Comment by MFenton1204** [comment]
yes, I fixed it by recreating the cert share container using adedit once done restart all services , but my main problem was the service account used for the service once I put the correct service account in and restarted services all was good.
